-- ============================================================================
-- ORCA — Flyway baseline (DON'T FILL THIS FILE WITH SCHEMA).
--
-- Quyết định kiến trúc (Quick Win F1.1):
-- ----------------------------------------------------------------------------
-- Schema gốc (~29 entities) được JPA/Hibernate tạo qua `ddl-auto=update` /
-- `ddl-auto=create-drop` ở các dev/test profile. Viết baseline SQL thủ công
-- cho 29 entity → quá rủi ro (sai index, sai FK, sai column type).
--
-- Thay vào đó, file V1__init.sql là NO-OP placeholder. Khi migrate sang Flyway
-- thật, cần 1 trong 2 cách:
--
-- CÁCH A (khuyến nghị cho prod): Dump schema từ DB hiện tại
--   1. Kết nối vào PostgreSQL hiện tại (đang có data).
--   2. `pg_dump --schema-only --no-owner orca_db > V1__init.sql`
--   3. Đặt version = 1 và đánh dấu applied: `INSERT INTO flyway_schema_history
--      (version, description, type, script, checksum, installed_by, installed_on,
--      execution_time, success) VALUES (1, 'init', 'SQL', 'V1__init.sql', -1,
--      'orca', now(), 0, true);`
--   4. Từ V2 trở đi, mọi thay đổi schema đều viết SQL mới, KHÔNG sửa entity
--      mà không tạo V tương ứng.
--
-- CÁCH B (dùng cho test/dev H2): Bật Flyway + baseline-on-migrate
--   - Spring Boot auto-detect schema đã tồn tại, tạo flyway_schema_history
--     với version=1, không chạy V1 nếu file rỗng.
--   - Phù hợp H2 in-memory `create-drop` mode.
--
-- CÁCH C (cho fresh prod): Dump schema từ JPA
--   1. Tạo DB mới.
--   2. Set `spring.jpa.hibernate.ddl-auto=create` rồi chạy app 1 lần.
--   3. `pg_dump --schema-only orca_db > V1__init.sql`.
--   4. Đổi `ddl-auto=validate`.
--   5. Bật Flyway (`spring.flyway.enabled=true`).
--   6. Thay thế file placeholder này bằng dump.
--
-- Hiện tại: file này là placeholder. Để tránh Flyway fail khi apply V2
-- (chat_attachments), test profile có `spring.flyway.enabled=false` (xem
-- application.properties). Migration order thực tế:
--   - V1__init.sql        (placeholder — schema do JPA tạo)
--   - V1_1__baseline_indexes.sql  (placeholder — index do JPA tạo)
--   - V2__add_chat_attachments.sql  (ALTER TABLE — chạy được cả H2 lẫn PG)
--
-- Cảnh báo: KHÔNG thêm index/column/FK vào entity mà quên tạo V tương ứng.
-- Trước khi merge PR có sửa entity, kiểm tra cần V__?.sql mới không.
-- ============================================================================
